"""Digest Writer Agent — compiles weekly findings into a publishable report.

Runs weekly. Reads the corpus, hypotheses tracker, and trial data.
Produces a markdown digest AND an HTML page for the website.
Style: Andrew Ng's "The Batch" meets Karpathy's technical depth.
"""

import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from llm import ask

ROOT = Path(__file__).parent.parent.parent
CORPUS_FILE = ROOT / "data" / "corpus.json"
HYPOTHESES_FILE = ROOT / "data" / "hypotheses_tracker.json"
DATA_FILE = ROOT / "data" / "data.json"
DIGESTS_DIR = ROOT / "data" / "digests"


def load_json(path):
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}


def get_recent_papers(corpus, days=7):
    """Get papers discovered in the last N days."""
    cutoff = (datetime.now() - timedelta(days=days)).isoformat()
    recent = []
    for pmid, paper in corpus.get("papers", {}).items():
        if paper.get("discovered", "") >= cutoff:
            recent.append(paper)
    return sorted(recent, key=lambda p: p.get("discovered", ""), reverse=True)


def write_digest(recent_papers, hypotheses, trial_data):
    """Use LLM to write the weekly digest."""
    # Prepare summaries
    paper_summaries = []
    for p in recent_papers[:10]:
        analysis = p.get("analysis", {})
        if analysis:
            paper_summaries.append(
                f"- [{p['pmid']}] {p['title']} ({p.get('journal','')}): {analysis.get('finding','?')}"
            )

    hyp_summaries = []
    for h in hypotheses.get("hypotheses", []):
        scores = h.get("scores", [])
        trend = "improving" if len(scores) > 1 and scores[-1] > scores[-2] else "declining" if len(scores) > 1 and scores[-1] < scores[-2] else "stable"
        hyp_summaries.append(f"- {h['drug']} → {h['target']}: score {scores[-1]}/100 ({trend})")

    stats = trial_data.get("stats", {})

    prompt = f"""Write a weekly HD research digest in the style of Andrew Ng's "The Batch" newsletter.
Be educational, accessible, and grounded. Lead with what matters most.
Use "we" voice — we're a small open-source project sharing what our AI agents found this week.

This week's data:
- {len(recent_papers)} new papers discovered by our Paper Scout agent
- {stats.get('trials_count', 0)} active clinical trials ({stats.get('recruiting_count', 0)} recruiting)

Paper highlights:
{chr(10).join(paper_summaries) if paper_summaries else "No new papers this week."}

Hypothesis tracker:
{chr(10).join(hyp_summaries)}

Write the digest with these sections:
1. "This Week in HD Research" — 2-3 paragraph overview of the most interesting findings
2. "What Our AI Found" — highlight 2-3 specific papers and what the LLM extracted
3. "Hypothesis Watch" — how our drug repurposing scores are trending
4. "One Thing to Think About" — a thought-provoking question or observation

Keep it under 800 words. No hype. No clinical claims. Cite PubMed IDs when referencing papers."""

    return ask(prompt, system="You are writing a research digest for the HD Research Hub. Style: Andrew Ng's The Batch — accessible, educational, data-driven. You are a data scientist, not a doctor.", temperature=0.4)


def run():
    print(f"\n{'='*50}")
    print(f"Digest Writer — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"{'='*50}\n")

    corpus = load_json(CORPUS_FILE)
    hypotheses = load_json(HYPOTHESES_FILE)
    trial_data = load_json(DATA_FILE)

    recent_papers = get_recent_papers(corpus, days=7)
    print(f"  Papers from last 7 days: {len(recent_papers)}")

    if not recent_papers and not hypotheses:
        print("  No new data to digest. Run paper_scout first.")
        return

    # Write digest
    print("  Writing digest with LLM...\n")
    digest_md = write_digest(recent_papers, hypotheses, trial_data)

    # Save
    DIGESTS_DIR.mkdir(parents=True, exist_ok=True)
    week_str = datetime.now().strftime("%Y-W%U")
    digest_file = DIGESTS_DIR / f"digest-{week_str}.md"

    header = f"""# HD Research Hub — Weekly Digest
*Week of {datetime.now().strftime('%B %d, %Y')}*
*Auto-generated by our Digest Writer agent*

---

"""
    footer = """

---

*This digest was written by an AI agent analyzing papers from PubMed and scoring drug repurposing hypotheses. It is not medical advice. All findings are exploratory. [View our methodology on GitHub](https://github.com/jravinder/hd-research-agent).*

*Bold like Jensen. Rigorous like Karpathy. Educational like Ng. Grounded like Fei-Fei Li. Innovative like Musk.*
"""

    with open(digest_file, "w") as f:
        f.write(header + digest_md + footer)

    print(f"  Saved: {digest_file}")
    print(f"\n{digest_md[:500]}...")
    print(f"\n{'='*50}")
    print(f"  Digest complete: {digest_file}")
    print(f"{'='*50}\n")


if __name__ == "__main__":
    run()
